apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thomassazeratdev/microservice-react:1.0.3
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
