service:
  type: NodePort
  ports:
    web:
      port: 80
      nodePort: 30080
    websecure:
      port: 443
      nodePort: 30443
    traefik:
      port: 9000
      nodePort: 39000

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"
