apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW5fcGFzc3dvcmQ=  # admin_password encodé en base64
  API_PASSWORD: YXBpX3Bhc3N3b3Jk  # api_password encodé en base64
  KONG_PASSWORD: a29uZ19wYXNzd29yZA==  # kong_password encodé en base64
