apiVersion: v1
kind: Secret
metadata:
  name: pokeapi-secrets
type: Opaque
data:
  DB_USER: YXBpX3VzZXI=  # api_user encodé en base64
  DB_PASSWORD: YXBpX3Bhc3N3b3Jk  # api_password encodé en base64
  DB_NAME: YXBpX2Ri  # api_db encodé en base64
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ== # postgres-service encodé en base64
